on:
  push:
    paths:
      - '**/*.go'
      - '**/*.mod'
      - '**/*.sum'
      - '**/*.yml'
name: CI
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  test:
    strategy:
      matrix:
        go-version: [dev-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: kevincobain2000/action-gobrew@v2
        with:
          version: ${{ matrix.go-version }}

      - name: Install Tools
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          go install github.com/axw/gocov/gocov@latest
          go install github.com/AlekSi/gocov-xml@latest

      - name: Test
        run: |
          go test -race -v ./... -count=1
      - name: Lint
        run: |
          gosec ./...
          go vet -all .

